KEYCOMBOE_ENABLE = no
AUTO_SHIFT_ENABLE = no

MOUSEKEY_ENABLE = yes
OLED_ENABLE = yes
CONSOLE_ENABLE = yes

KEY_OVERRIDE_ENABLE = no

DEFERRED_EXEC_ENABLE = yes


PROGRAM_CMD =  pico-dfu -y $(BUILD_DIR)/$(TARGET).uf2

NKRO_ENABLE = no

KEYBOARD_SHARED_EP = yes

SPLIT_LCD_FEATURE = yes

OPT_DEFS += -DOLED_BRIGHTNESS=120 -DMK_KINETIC_SPEED -DMOUSEKEY_INITIAL_SPEED=420
