
#define MK_KINETIC_SPEED
#define MOUSEKEY_MAX_SPEED 4
#define MOUSEKEY_MOVE_DELTA 	20
#define MOUSEKEY_INITIAL_SPEED 	300
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_ACCELERATED_SPEED 	4000

#define MATRIX_IO_DELAY 40

#define DEBOUNCE 3

//#define DEBUG_MATRIX_SCAN_RATE
