
#define MK_KINETIC_SPEED
#define MOUSEKEY_MAX_SPEED 4
#define MOUSEKEY_MOVE_DELTA 	30
#define MOUSEKEY_INITIAL_SPEED 	500
#define MOUSEKEY_BASE_SPEED 	4000
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_ACCELERATED_SPEED 	4000

//#define MATRIX_IO_DELAY 40
//#define DEBUG_MATRIX_SCAN_RATE

#define DEBOUNCE 7

