COMBO_ENABLE = yes
AUTO_SHIFT_ENABLE = no
KEY_OVERRIDE_ENABLE = no
NKRO_ENABLE = no
TRI_LAYER_ENABLE = yes
NO_SUSPEND_POWER_DOWN = yes

CONSOLE_ENABLE = yes

OS_DETECTION_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes

PROGRAM_CMD =  pico-dfu -y $(BUILD_DIR)/$(TARGET).uf2

KEYBOARD_SHARED_EP = yes

SPLIT_LCD_FEATURE = yes
OLED_DRIVER_ENABLE = yes
WPM_ENABLE = yes
KEYCODE_STRING_ENABLE = yes

OPT_DEFS += -DOLED_BRIGHTNESS=120 -DMK_KINETIC_SPEED -DMOUSEKEY_INITIAL_SPEED=380 -DMOUSEKEY_BASE_SPEED=2000

SRC += win_def_layer.c
