KEYCOMBOE_ENABLE = no
AUTO_SHIFT_ENABLE = no
KEY_OVERRIDE_ENABLE = no
NKRO_ENABLE = no
TRI_LAYER_ENABLE = yes

CONSOLE_ENABLE = yes

DEFERRED_EXEC_ENABLE = yes

PROGRAM_CMD =  pico-dfu -y $(BUILD_DIR)/$(TARGET).uf2

KEYBOARD_SHARED_EP = yes

SPLIT_LCD_FEATURE = yes

OPT_DEFS += -DOLED_BRIGHTNESS=120 -DMK_KINETIC_SPEED -DMOUSEKEY_INITIAL_SPEED=380 -DMOUSEKEY_BASE_SPEED=2000
