
#define MK_KINETIC_SPEED 1
#define MOUSEKEY_MAX_SPEED 4
#define MOUSEKEY_MOVE_DELTA 	30
#define MOUSEKEY_INITIAL_SPEED 	500
#define MOUSEKEY_BASE_SPEED 	4000
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_ACCELERATED_SPEED 	4000
#define MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS 60

//#define MATRIX_IO_DELAY 40
//#define DEBUG_MATRIX_SCAN_RATE

#define DEBOUNCE 10

//per key timeout for leader key
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250

#define TAPPING_TERM 200

#define RETRO_TAPPING
#define PERMISSIVE_HOLD
#undef  HOLD_ON_OTHER_KEY_PRESS
